version: '3.8'

services:
  extractbrowser:
    build: .
    container_name: extractbrowser
    restart: always
    ports:
      - "2345:2345"
    env_file:
      - .env
    environment:
      - PORT=2345
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
